name: Send config to inspector
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read JSON
        id: read_config
        run: |
          json=$(cat config/inspector.json)
          echo "::set-output name=config::$json"
        shell: bash

      - name: Validate JSON
        run: |
          config=${{ fromJSON(steps.read_config.outputs.config) }}
          owner=${{ config.owner }}
          repo=${{ config.repo }}
          useSimpleSummary=${{ config.useSimpleSummary }}

          if [[ ! "$owner" =~ ^[a-zA-Z0-9]+$ ]]; then
            echo "owner must be alphanumeric and at least 1 character long"
            exit 1
          fi
          if [[ ! "$repo" =~ ^[a-zA-Z0-9]+$ ]]; then
            echo "repo must be alphanumeric and at least 1 character long"
            exit 1
          fi
          if [[ ! "$useSimpleSummary" =~ ^(true|false)$ ]]; then
            echo "useSimpleSummary must be a boolean"
            exit 1
          fi
        env:
          owner: ${{ config.owner }}
          repo: ${{ config.repo }}
          useSimpleSummary: ${{ config.useSimpleSummary }}
